config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :pdf, only: :create, controller: :pdf do
    member do
      get :signature
      get :download
    end
  end


  post 'mifiel', controller: :hooks, action: :mifiel
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord

  attr_accessor :text

  has_many :users, through: :signatures
  has_many :signatures
  accepts_nested_attributes_for :users, allow_destroy: true

  before_save :send_pdf

  def generate_pdf!
    pdf_file = Prawn::Document.new
    pdf_file.text self.text
    self.pdf = Base64.urlsafe_encode64(pdf_file.render)
    self.hsh = Digest::SHA256.hexdigest pdf_file.render
  end

  def send_pdf
    return unless widget_id.nil?
    # TODO Add to background job
    mf_document = Mifiel::Document.create(
      hash: hsh,
      name: 'document.pdf',
      callback_url: Rails.application.secrets.mifiel_callback_url,
      signatories: users_params
    )
    self.widget_id = mf_document.widget_id
    self.document_id = mf_document.id
  end

  def users_params
    # Test widget integration without real info
    # users_set = users.select(:name, :email, :tax_id)
    # ary = JSON.parse(users_set.to_json)
    # ary.map{|e| e.delete_if{|k, v| k == 'id'} }
    [
      {
        name: 'Luis',
        email: 'luisguzman02@hotmail.com'
      },
      {
        name: 'Luis',
        email: 'luisguzman@outlook.com'
      }
    ]
  end

  %w(xml pdf).each do |action|
    define_method "#{action}_path" do
      Rails.root.join("public/data/document-#{id}.#{action}")
    end
  end
end

app/models/hooks/mifiel.rb
module Hooks
  class Mifiel
    attr_accessor :response, :head, :document

    def initialize(params)
      self.response = params
      default_head
    end

    def default_head
      self.head = { status: 200, content_type: "text/plain" }
    end

    def fetch_files!
      self.document = Document.find_by_document_id(response.fetch(:id))
      # TODO add requests to background jobs
      mf_document = ::Mifiel::Document.find(document.document_id)
      mf_document.save_xml(document.xml_path)
      mf_document.save_file_signed(document.pdf_path)
    end

    def merge_files!
      merge_xml
      merge_pdf
    end

    def merge_xml
      doc = File.read(document.xml_path)
      xml = Nokogiri.XML(doc)
      xml.at(:file).content = document.pdf
      File.open(document.xml_path, 'w') { |f| f.puts xml.to_xml }
    end

    def merge_pdf
      File.open(document.pdf_path.to_s.gsub(/.pdf/, '-orig.pdf'), "wb") do |f|
        f.write(Base64.urlsafe_decode64(document.pdf))
      end
      doc = File.read(document.pdf_path)
      Prawn::Document.generate(document.pdf_path, template: document.pdf_path.to_s.gsub(/.pdf/, '-orig.pdf')) do |pdf|
        pdf.go_to_page(pdf.page_count)
        pdf.start_new_page(template: document.pdf_path)
      end
    end
  end
end

app/models/signature.rb
class Signature < ApplicationRecord

  belongs_to :document
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_many :documents, through: :signatures
  has_many :signatures

  validates_presence_of :name, :email, :tax_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def mifiel
    hook = Hooks::Mifiel.new(params)
    hook.fetch_files!
    hook.merge_files!
    head hook.head
  end
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  before_action :set_document, only: [:signature, :download]

  def create
    doc = Document.new(document_params.merge(text: render_to_string(partial: '/home/billing')))
    doc.generate_pdf!
    if doc.save
      redirect_to signature_pdf_path(id: doc.id)
    else
      redirect_to root_path, message: 'Failed to generate pdf'
    end
  end

  def signature
    if check_signatures
      return render 'document'
    end
  end

  def download
    path = "#{Rails.root}/public/data/document-#{@document.id}.#{params[:format]}"
    send_file path, type: "application/pdf", x_sendfile: true
  end

  private
  def set_document
    @document = Document.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path if @document.nil?
  end

  def document_params
    params.require(:document).permit(users_attributes: [:name, :email, :tax_id])
  end

  def check_signatures
    mf_document = Mifiel::Document.find(@document.document_id)
    mf_document.signed || !mf_document.status.first.zero?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdf_helper.rb
module PdfHelper

  def files_received?(document)
    File.exists?(document.pdf_path) && File.exists?(document.xml_path)
  end
end

app/views/home/_billing.html.erb
<header>
  <h1>Invoice</h1>
  <address contenteditable>
    <p>Luis Guzman</p>
    <p>Las Pampas #6<br>Hermosillo, SON 83220</p>
    <p>(662) 111-5191</p>
  </address>
</header>
<article>
  <h1>Recipient</h1>
  <address contenteditable>
    <p>Some Company<br>c/o Some Guy</p>
  </address>
  <table class="meta">
    <tr>
      <th><span contenteditable>Invoice #</span></th>
      <td><span contenteditable>101138</span></td>
    </tr>
    <tr>
      <th><span contenteditable>Date</span></th>
      <td><span contenteditable>January 1, 2017</span></td>
    </tr>
    <tr>
      <th><span contenteditable>Amount Due</span></th>
      <td><span id="prefix" contenteditable>$</span><span>600.00</span></td>
    </tr>
  </table>
  <table class="inventory">
    <thead>
      <tr>
        <th><span contenteditable>Item</span></th>
        <th><span contenteditable>Description</span></th>
        <th><span contenteditable>Rate</span></th>
        <th><span contenteditable>Quantity</span></th>
        <th><span contenteditable>Price</span></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><a class="cut">-</a><span contenteditable>Front End Consultation</span></td>
        <td><span contenteditable>Experience Review</span></td>
        <td><span data-prefix>$</span><span contenteditable>150.00</span></td>
        <td><span contenteditable>4</span></td>
        <td><span data-prefix>$</span><span>600.00</span></td>
      </tr>
    </tbody>
  </table>
  <a class="add">+</a>
  <table class="balance">
    <tr>
      <th><span contenteditable>Total</span></th>
      <td><span data-prefix>$</span><span>600.00</span></td>
    </tr>
    <tr>
      <th><span contenteditable>Amount Paid</span></th>
      <td><span data-prefix>$</span><span contenteditable>0.00</span></td>
    </tr>
    <tr>
      <th><span contenteditable>Balance Due</span></th>
      <td><span data-prefix>$</span><span>600.00</span></td>
    </tr>
  </table>
</article>
<aside>
  <h1><span contenteditable>Additional Notes</span></h1>
  <div contenteditable>
    <p>A finance charge of 1.5% will be made on unpaid balances after 30 days.</p>
  </div>
</aside>
</body>

app/views/home/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Firma tu documento</h3>
  </div>

  <div class="panel-body">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 well well-sm">
        <%= render partial: 'home/billing' %>
      </div>
    </div>
    <%= form_tag pdf_index_path, method: :post, class: 'form-horizontal' do %>
      <div class="row">
        <div class="col-md-6 col-md-offset-1">
          <h4>Firmante 1: </h4>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-10">
              <%= text_field_tag 'document[users_attributes][][name]', '', class: 'form-control', placeholder: 'Nombre', required: true %>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <%= text_field_tag 'document[users_attributes][][email]', '', class: 'form-control', placeholder: 'Email', required: true %>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-10">
              <%= text_field_tag 'document[users_attributes][][tax_id]', '', class: 'form-control', placeholder: 'RFC', required: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-1">
          <h4>Firmante 2: </h4>
          <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-10">
              <%= text_field_tag 'document[users_attributes][][name]', '', class: 'form-control', placeholder: 'Nombre', required: true %>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <%= text_field_tag 'document[users_attributes][][email]', '', class: 'form-control', placeholder: 'Email', required: true %>
            </div>
          </div>
          <div class="form-group">
            <label for="" class="col-sm-2 control-label">RFC</label>
            <div class="col-sm-10">
              <%= text_field_tag 'document[users_attributes][][tax_id]', '', class: 'form-control', placeholder: 'RFC', required: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-1">

          <%= submit_tag 'Create PDF', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MifielTest</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', integrity: "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", crossorigin: "anonymous" %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
        </div>

        <%= link_to 'FUN Test', root_path, class: 'navbar-brand' %>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
            </li>
            <li></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pdf/document.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <h4>Aqui puedes descargar tu documento firmado</h4>
  </div>
</div>

<div class="row">
  <% if files_received?(@document) %>
    <div class="col-md-5 col-md-offset-1">
      <%= link_to 'Descargar PDF firmado', download_pdf_path(@document, format: :pdf), class: 'btn btn-primary' %>
    </div>
    <div class="col-md-5 col-md-offset-1">
      <%= link_to 'Descargar XML', download_pdf_path(@document, format: :xml), class: 'btn btn-primary' %>
    </div>
  <% else %>
    <div class="col-md-10 col-md-offset-1">
      <p>
        <span class="label label-warning">
          Las firmas del documento (<%= @document.id %>) estan siendo procesadas
        </span>
      </p>
      <br/>
      <br/>
      <br/>
      <%= link_to 'Firmar un nuevo documento', root_path, class: 'btn btn-info' %>
    </div>
  <% end %>
</div>

app/views/pdf/signature.html.erb
<script type="text/javascript">
  window.mifiel=window.mifiel||[],function(){"use strict";for(var e=["widget"],i=function(e){return function(){window.mifiel.push([e].concat(Array.prototype.slice.call(arguments,0)))}},t=0;t<e.length;t++){var n=e[t];window.mifiel[n]||(window.mifiel[n]=i(n))}if(!document.getElementById("mifiel-js")){var r=document.createElement("script"),o=document.getElementsByTagName("script")[0];r.type="text/javascript",r.id="mifiel-js",r.async=!0,r.src="https://sandbox.mifiel.com/sign-widget-v1.0.0.js",o.parentNode.insertBefore(r,o)}}();
</script>

<script type="text/javascript">
  window.mifiel.widget({
    widgetId: "<%= @document.widget_id %>",
    appendTo: 'widget-integration',
    successBtnText: 'Proceed to next step',
    pdf: "<%= @document.pdf %>"
  });
</script>


<script type="text/javascript">
  window.addEventListener('message', function (e) {
    console.log(e);
    // accept messages from known hosts only
    // change to https://stageex.mifiel.com if necessary
    // if (e.origin !== 'https://www.mifiel.com') {
    //   return;
    // }
    // We will always send an object
    if (typeof e.data !== 'object') {
      return;
    }
    // document signed succesfully
    if (e.data.eventType === 'mifiel.widget.success') {
      var data = e.data,
          doc = data.document,
          signature = data.signature;
      // doc.original_hash;
      // doc.file_signed;
      window.top.location.reload();
    }
    // Event errors
    if (e.data.eventType === 'mifiel.widget.error') {
      var error = e.data.error;
      // error.code => 1001
      // error.message => 'Invalid PDF, the pdf param has no data'
    }
  }, false);
</script>

<div id="widget-integration">
</div>